services:
  postgres:
    image: postgres:17
    container_name: language_learning_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@Baduc2509'
      POSTGRES_DB: language_learning_db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
